apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090      # gọi bằng TÊN SERVICE trong mạng Docker
    isDefault: true
    editable: false                  # không cho sửa tay -> buộc mọi thay đổi qua file
