apiVersion: v1
kind: Pod                      # Pod "trần" — không ai quản lý nó
metadata:
  name: web-tran
  labels:
    app: thu-nghiem
spec:
  containers:
    - name: web
      image: nginx:1.27        # tag cụ thể, KHÔNG dùng :latest
      ports:
        - containerPort: 80
      resources:               # xin tài nguyên vừa đủ, tránh chiếm hết máy
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
