FROM debian:12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends openssh-server python3 sudo && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /run/sshd

# Tạo user để Ansible đăng nhập, cho sudo không cần mật khẩu
RUN useradd -m -s /bin/bash quantri && \
    echo "quantri ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/quantri && \
    mkdir -p /home/quantri/.ssh && chmod 700 /home/quantri/.ssh

COPY khoa_lab.pub /home/quantri/.ssh/authorized_keys
RUN chown -R quantri:quantri /home/quantri/.ssh && \
    chmod 600 /home/quantri/.ssh/authorized_keys

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
