apiVersion: v1
kind: Secret
metadata:
  name: bi-mat-app
type: Opaque
stringData:                     # stringData: viết chữ thường, K8s tự mã hoá base64 giúp
  MAT_KHAU_DB: "MatKhauSieuBiMat123"
  KHOA_API: "sk-abc123xyz789"
